version: '3'
services:
  ircserv:
    container_name: ircserv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1024:1024"
      - "1025:1025"
      - "1026:1026"
      - "1027:1027"
      - "1028:1028"
      - "1029:1029"
      - "1030:1030"
    volumes:
      - ./inc/:/app/inc
      - ./srcs/:/app/srcs
      - ./objs/:/app/objs
